CREATE TABLE roles(
    id SERIAL PRIMARY KEY,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE users (
    tg_id BIGINT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    role_id INTEGER NOT NULL,
    document VARCHAR(60) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);
