CREATE TABLE IF NOT EXISTS roles(
    id SERIAL PRIMARY KEY,
    role VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    tg_id BIGINT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    role_id INTEGER NOT NULL,
    phone VARCHAR(12) UNIQUE,
    document VARCHAR(60) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS blacklist (
    tg_id BIGINT PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    phone VARCHAR(12)
);